# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: /#about
    weight: 10
    
  - name: Skills
    pageRef: skills
    weight: 11

  - name: Experience
    pageRef: experience
    weight: 20

  - name: Projects
    pageRef: projects
    identifier: projects
    weight: 30

  - name: 웹 프론트엔드 개발
    pageRef: projects/web-frontend   
    parent: projects
    weight: 31

  - name: UI/UX 디자인
    pageRef: projects/ui-ux
    parent: projects
    weight: 32

  - name: Contact
    pageRef: contact
    weight: 40
